import {createHmac,timingSafeEqual} from "node:crypto"; import type {BillingInterval,Plan,SubscriptionStatus} from "./entitlements";
function key(){const v=process.env.STRIPE_SECRET_KEY?.trim();if(!v)throw new Error("STRIPE_SECRET_KEY is not configured.");return v}
function price(plan:Plan,interval:BillingInterval){const id=process.env[plan==="core"?(interval==="month"?"STRIPE_CORE_MONTHLY_PRICE_ID":"STRIPE_CORE_ANNUAL_PRICE_ID"):(interval==="month"?"STRIPE_PRO_MONTHLY_PRICE_ID":"STRIPE_PRO_ANNUAL_PRICE_ID")]||"";if(!id)throw new Error("Stripe price ID is not configured.");return id}
async function stripe(path:string,init:RequestInit={}){return fetch("https://api.stripe.com/v1/"+path,{...init,headers:{Authorization:"Bearer "+key(),...(init.headers||{})},cache:"no-store"})}
function form(values:Record<string,string|number|undefined>){const p=new URLSearchParams();for(const[k,v]of Object.entries(values))if(v!==undefined)p.set(k,String(v));return p}
export async function stripeCustomer(email:string,userId:string){const s=await stripe("customers/search?query="+encodeURIComponent("metadata['supabase_user_id']:'"+userId+"'"));if(s.ok){const d=await s.json();if(d.data?.[0]?.id)return d.data[0].id}const r=await stripe("customers",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form({"email":email,"metadata[supabase_user_id]":userId}).toString()});if(!r.ok)throw new Error("Could not create Stripe customer.");return(await r.json()).id}
export async function createCheckout(customer:string,userId:string,plan:Plan,interval:BillingInterval){const site=(process.env.NEXT_PUBLIC_SITE_URL||"https://theclearcfo.com").replace(/\/$/,"");const r=await stripe("checkout/sessions",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form({mode:"subscription",customer,"line_items[0][price]":price(plan,interval),"line_items[0][quantity]":1,trial_period_days:7,success_url:site+"/api/billing/return?session_id={CHECKOUT_SESSION_ID}",cancel_url:site+"/customer/briefing?billing=cancelled","metadata[supabase_user_id]":userId,"metadata[plan]":plan,"metadata[interval]":interval,"subscription_data[metadata][supabase_user_id]":userId,"subscription_data[metadata][plan]":plan,"subscription_data[metadata][interval]":interval}).toString()});if(!r.ok){const t=await r.text();throw new Error(t.slice(0,500))}return await r.json()}
export async function stripeGet(path:string){const r=await stripe(path);if(!r.ok)throw new Error("Stripe request failed.");return r.json()}
export async function upsertSubscription(row:Record<string,unknown>){const r=await sb("subscriptions",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});if(!r.ok)throw new Error("Could not save subscription.")}
async function sb(path:string,init:RequestInit={}){const url=process.env.SUPABASE_URL?.replace(/\/$/,""),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server configuration is missing.");return fetch(url+"/rest/v1/"+path,{...init,headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"})}
export async function verifyStripeSignature(raw:string,header:string|null){const secret=process.env.STRIPE_WEBHOOK_SECRET?.trim();if(!secret||!header)return false;const parts=Object.fromEntries(header.split(",").map(x=>x.split("=")).filter(x=>x.length===2));const timestamp=Number(parts.t),sig=parts.v1;if(!timestamp||!sig||Math.abs(Date.now()/1000-timestamp)>300)return false;const expected=createHmac("sha256",secret).update(timestamp+"."+raw).digest("hex");try{return timingSafeEqual(Buffer.from(expected,"hex"),Buffer.from(sig,"hex"))}catch{return false}}
export function mapStatus(status:string):SubscriptionStatus{return status==="trialing"?"trialing":status==="active"?"active":status==="past_due"?"past_due":"canceled"}
